### ISSUE TITLE
Add change detection

### ISSUE THREAD

**Issue by nth29** [pblottiere/littodyn#1]
Add change detection algo.

**Comment by nth29** [comment]
Change detection will take as input:
- 2 multispectral images
- A ROI polygon

2 input images are supposed to have same size, same number of bands at same wavelength
ROI polygon is supposed to be in the same projection that input images.

The ouput is one band dataset were greater values indicate strong change between the 2 input images, pixels outside the ROI polygon are masked with nodata.

**Comment by nth29** [comment]
A first version with simple euclidian distance is avaible.
 @pblottiere : Waiting for permission to push on the repository (new branch change_detector)

**Comment by nth29** [comment]
A more sophisticated algo using PCA, with sklearnand scipy dependencies is available here :
https://github.com/abhijeet3922/Change-Detection-in-Satellite-Imagery/blob/master/PCAKmeans.py

Some details here : 

https://appliedmachinelearning.blog/2017/11/25/unsupervised-changed-detection-in-multi-temporal-satellite-images-using-pca-k-means-python-code/


Trying to integrate this algo...

**Comment by pblottiere** [comment]
> Waiting for permission to push on the repository (new branch change_detector)

@nth29 I've just sent you an invitation.

But FYI, the GitHub workflow is:

1. fork the upstream repository
2. create a branch on your fork
3. create a Pull Request for discussion (same thing as Merge Request on GitLab)

**Comment by nth29** [comment]
Sorry, new with github workflow, will do that.

**Comment by pblottiere** [comment]
> Sorry, new with github workflow, will do that.

Don't worry, you can just push your branch for this time :).

**Comment by nth29** [comment]
Pull Request created

**Comment by pblottiere** [comment]
Resolved with https://github.com/pblottiere/littodyn/pull/2
